package com.adnan.entity;
// Generated Aug 23, 2020, 2:32:21 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Answer generated by hbm2java
 */
@Entity
@Table(name = "answer", catalog = "surveys")
public class Answer implements java.io.Serializable {

	private int id;
	private Questions questions;
	private String answer;
	private String comment;

	public Answer() {
	}

	public Answer(int id, Questions questions, String answer) {
		this.id = id;
		this.questions = questions;
		this.answer = answer;
	}

	public Answer(int id, Questions questions, String answer, String comment) {
		this.id = id;
		this.questions = questions;
		this.answer = answer;
		this.comment = comment;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "questions_id", nullable = false)
	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

	@Column(name = "answer", nullable = false, length = 45)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Column(name = "comment", length = 45)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
