package com.adnan.entity;
// Generated Aug 23, 2020, 2:32:21 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Survey generated by hbm2java
 */
@Entity
@Table(name ="survey1", catalog = "surveys", uniqueConstraints = { @UniqueConstraint(columnNames = "creator"),
		@UniqueConstraint(columnNames = "name") })
public class Survey implements java.io.Serializable {

	private int id;
	private String name;
	private String creator;
	private String email;
	private Set<Questions> questionses = new HashSet<Questions>(0);

	public Survey() {
	}

	public Survey(int id, String name, String creator) {
		this.id = id;
		this.name = name;
		this.creator = creator;
	}

	public Survey(int id, String name, String creator, String email, Set<Questions> questionses) {
		this.id = id;
		this.name = name;
		this.creator = creator;
		this.email = email;
		this.questionses = questionses;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="id")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "creator", unique = true, nullable = false, length = 45)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "survey")
	public Set<Questions> getQuestionses() {
		return this.questionses;
	}

	public void setQuestionses(Set<Questions> questionses) {
		this.questionses = questionses;
	}

}
